version: '3'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: partner_db
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/partner_db?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
volumes:
  db_data:
